apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        chaos/app-instance: demo
        chaos/app-group: demo
    spec:
      containers:
      - name: demo
        image: docker.io/library/demo:1.0.0
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - name: http
    port: 8000
    targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.demo.com
    http:
      paths:
      - path: /admin/?(.*)
        backend:
          service:
            name: demo
            port: 
              name: http
        pathType: Prefix